auto-create logs directory
Signed-off-by: Andrew Whitehead <cywolf@gmail.com>

diff --git a/demo/run_demo b/demo/run_demo
--- a/demo/run_demo
+++ b/demo/run_demo
@@ -7,6 +7,17 @@ cd $(dirname $0)
 AGENT="$1"
 shift
 
+case "$@" in *--timing*)
+	if [ ! -d "../logs" ]; then
+		mkdir ../logs && chmod -R uga+rws ../logs
+	fi
+	if [ "$(ls -ld ../logs | grep dr..r..rwx)" == "" ]; then
+		echo "Error: To use the --timing parameter, the directory '../logs' must exist and all users must be able to write to it."
+		echo "For example, to create the directory and then set the permissions use: 'mkdir ../logs; chmod uga+rws ../logs'"
+		exit 1
+	fi
+esac
+
 if [ "$AGENT" = "faber" ]; then
 	AGENT_MODULE="faber"
 	AGENT_PORT=8020
